// Mocks generated by Mockito 5.4.4 from annotations
// in zippy/test/unit/auth/auth_repository_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:zippy/domain/model/auth/auth_inititate_model.dart' as _i2;
import 'package:zippy/domain/model/auth/auth_refresh_mode.dart' as _i4;
import 'package:zippy/domain/model/auth/auth_verify_model.dart' as _i3;
import 'package:zippy/domain/repository/auth/auth_repository.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthInitiate_0 extends _i1.SmartFake implements _i2.AuthInitiate {
  _FakeAuthInitiate_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthVerify_1 extends _i1.SmartFake implements _i3.AuthVerify {
  _FakeAuthVerify_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthRefresh_2 extends _i1.SmartFake implements _i4.AuthRefresh {
  _FakeAuthRefresh_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i5.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.AuthInitiate> initiateAuth(
          String? phone, String? countryCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #initiateAuth,
          [phone],
        ),
        returnValue: _i6.Future<_i2.AuthInitiate>.value(_FakeAuthInitiate_0(
          this,
          Invocation.method(
            #initiateAuth,
            [phone],
          ),
        )),
      ) as _i6.Future<_i2.AuthInitiate>);

  @override
  _i6.Future<_i3.AuthVerify> verifyAuth(
    String? code,
    String? phone,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyAuth,
          [
            code,
            phone,
            userId,
          ],
        ),
        returnValue: _i6.Future<_i3.AuthVerify>.value(_FakeAuthVerify_1(
          this,
          Invocation.method(
            #verifyAuth,
            [
              code,
              phone,
              userId,
            ],
          ),
        )),
      ) as _i6.Future<_i3.AuthVerify>);

  @override
  _i6.Future<_i4.AuthRefresh> refreshAuth(String? refreshToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshAuth,
          [refreshToken],
        ),
        returnValue: _i6.Future<_i4.AuthRefresh>.value(_FakeAuthRefresh_2(
          this,
          Invocation.method(
            #refreshAuth,
            [refreshToken],
          ),
        )),
      ) as _i6.Future<_i4.AuthRefresh>);

  @override
  _i6.Future<bool> verifyToken(String? accessToken) => (super.noSuchMethod(
        Invocation.method(
          #verifyToken,
          [accessToken],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}
