// Mocks generated by Mockito 5.4.4 from annotations
// in zippy/test/unit/transfer/transfer_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:zippy/domain/model/transfer/transfer_model.dart' as _i2;
import 'package:zippy/domain/repository/transfer/transfer_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTransferInitiate_0 extends _i1.SmartFake
    implements _i2.TransferInitiate {
  _FakeTransferInitiate_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TransferRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransferRepository extends _i1.Mock
    implements _i3.TransferRepository {
  MockTransferRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.TransferInitiate> initiateTransfer(
          Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #initiateTransfer,
          [data],
        ),
        returnValue:
            _i4.Future<_i2.TransferInitiate>.value(_FakeTransferInitiate_0(
          this,
          Invocation.method(
            #initiateTransfer,
            [data],
          ),
        )),
      ) as _i4.Future<_i2.TransferInitiate>);
}
